package com.mocredit.bank.entity;

import java.util.Date;

public class TiPaymentReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.uuid
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private Integer uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.bank
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.terminal_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private String terminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.order_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.card_num
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.pos_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private String posId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.pos_time
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private String posTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.product_type
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.amount
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.status
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private Short status;
    private Object bankData;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.ctime
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_payment_report.device
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    private String device;
    private int requestId;
    private String transDate;
    
    public String getTransDate() {
		return transDate;
	}

	public void setTransDate(String transDate) {
		this.transDate = transDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.uuid
     *
     * @return the value of ti_payment_report.uuid
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.uuid
     *
     * @param uuid the value for ti_payment_report.uuid
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.bank
     *
     * @return the value of ti_payment_report.bank
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.bank
     *
     * @param bank the value for ti_payment_report.bank
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.terminal_id
     *
     * @return the value of ti_payment_report.terminal_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.terminal_id
     *
     * @param terminalId the value for ti_payment_report.terminal_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.order_id
     *
     * @return the value of ti_payment_report.order_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.order_id
     *
     * @param orderId the value for ti_payment_report.order_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.card_num
     *
     * @return the value of ti_payment_report.card_num
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.card_num
     *
     * @param cardNum the value for ti_payment_report.card_num
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.pos_id
     *
     * @return the value of ti_payment_report.pos_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public String getPosId() {
        return posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.pos_id
     *
     * @param posId the value for ti_payment_report.pos_id
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setPosId(String posId) {
        this.posId = posId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.pos_time
     *
     * @return the value of ti_payment_report.pos_time
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public String getPosTime() {
        return posTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.pos_time
     *
     * @param posTime the value for ti_payment_report.pos_time
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setPosTime(String posTime) {
        this.posTime = posTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.product_type
     *
     * @return the value of ti_payment_report.product_type
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.product_type
     *
     * @param productType the value for ti_payment_report.product_type
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.amount
     *
     * @return the value of ti_payment_report.amount
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.amount
     *
     * @param amount the value for ti_payment_report.amount
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.status
     *
     * @return the value of ti_payment_report.status
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.status
     *
     * @param status the value for ti_payment_report.status
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.ctime
     *
     * @return the value of ti_payment_report.ctime
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.ctime
     *
     * @param ctime the value for ti_payment_report.ctime
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_payment_report.device
     *
     * @return the value of ti_payment_report.device
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_payment_report.device
     *
     * @param device the value for ti_payment_report.device
     *
     * @mbggenerated Mon Aug 24 10:10:03 CST 2015
     */
    public void setDevice(String device) {
        this.device = device;
	}

	public Object getBankData() {
		return bankData;
	}

	public void setBankData(Object bankData) {
		this.bankData = bankData;
	}

	public int getRequestId() {
		return requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}
	
}