package com.mocredit.bank.entity;

public class TiReportDataZx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.uuid
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private Integer uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.merchant_id
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.merchant_name
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.batch_no
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.serial_no
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.authorizeCode
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private String authorizeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.authDate
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private String authDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.authTime
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private String authTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_report_data_zx.report_id
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    private Integer reportId;

    private String bankOrderId;
    private String retrievalNo;
    
    public String getRetrievalNo() {
		return retrievalNo;
	}

	public void setRetrievalNo(String retrievalNo) {
		this.retrievalNo = retrievalNo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.uuid
     *
     * @return the value of ti_report_data_zx.uuid
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.uuid
     *
     * @param uuid the value for ti_report_data_zx.uuid
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.merchant_id
     *
     * @return the value of ti_report_data_zx.merchant_id
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.merchant_id
     *
     * @param merchantId the value for ti_report_data_zx.merchant_id
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.merchant_name
     *
     * @return the value of ti_report_data_zx.merchant_name
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.merchant_name
     *
     * @param merchantName the value for ti_report_data_zx.merchant_name
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.batch_no
     *
     * @return the value of ti_report_data_zx.batch_no
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.batch_no
     *
     * @param batchNo the value for ti_report_data_zx.batch_no
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.serial_no
     *
     * @return the value of ti_report_data_zx.serial_no
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.serial_no
     *
     * @param serialNo the value for ti_report_data_zx.serial_no
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.authorizeCode
     *
     * @return the value of ti_report_data_zx.authorizeCode
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public String getAuthorizeCode() {
        return authorizeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.authorizeCode
     *
     * @param authorizecode the value for ti_report_data_zx.authorizeCode
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setAuthorizeCode(String authorizecode) {
        this.authorizeCode = authorizecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.authDate
     *
     * @return the value of ti_report_data_zx.authDate
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public String getAuthDate() {
        return authDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.authDate
     *
     * @param authdate the value for ti_report_data_zx.authDate
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setAuthDate(String authdate) {
        this.authDate = authdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.authTime
     *
     * @return the value of ti_report_data_zx.authTime
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public String getAuthTime() {
        return authTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.authTime
     *
     * @param authtime the value for ti_report_data_zx.authTime
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setAuthTime(String authtime) {
        this.authTime = authtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_report_data_zx.report_id
     *
     * @return the value of ti_report_data_zx.report_id
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_report_data_zx.report_id
     *
     * @param reportId the value for ti_report_data_zx.report_id
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

	public String getBankOrderId() {
		return bankOrderId;
	}

	public void setBankOrderId(String bankOrderId) {
		this.bankOrderId = bankOrderId;
	}
    
}