package com.mocredit.bank.entity;

public class TiShopMerchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_shop_merchant.uuid
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    private Integer uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_shop_merchant.merchant_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_shop_merchant.merchant_name
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_shop_merchant.merchant_password
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    private String merchantPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_shop_merchant.shop_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    private Integer shopId;
    
    private String token;
    private short status;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ti_shop_merchant.terminal_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    private String terminalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_shop_merchant.uuid
     *
     * @return the value of ti_shop_merchant.uuid
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_shop_merchant.uuid
     *
     * @param uuid the value for ti_shop_merchant.uuid
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_shop_merchant.merchant_id
     *
     * @return the value of ti_shop_merchant.merchant_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_shop_merchant.merchant_id
     *
     * @param merchantId the value for ti_shop_merchant.merchant_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_shop_merchant.merchant_name
     *
     * @return the value of ti_shop_merchant.merchant_name
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_shop_merchant.merchant_name
     *
     * @param merchantName the value for ti_shop_merchant.merchant_name
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_shop_merchant.merchant_password
     *
     * @return the value of ti_shop_merchant.merchant_password
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public String getMerchantPassword() {
        return merchantPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_shop_merchant.merchant_password
     *
     * @param merchantPassword the value for ti_shop_merchant.merchant_password
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public void setMerchantPassword(String merchantPassword) {
        this.merchantPassword = merchantPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_shop_merchant.shop_id
     *
     * @return the value of ti_shop_merchant.shop_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_shop_merchant.shop_id
     *
     * @param shopId the value for ti_shop_merchant.shop_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ti_shop_merchant.terminal_id
     *
     * @return the value of ti_shop_merchant.terminal_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ti_shop_merchant.terminal_id
     *
     * @param terminalId the value for ti_shop_merchant.terminal_id
     *
     * @mbggenerated Tue Aug 25 10:03:40 CST 2015
     */
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public short getStatus() {
		return status;
	}

	public void setStatus(short status) {
		this.status = status;
	}
    
}