package com.mocredit.bank.entity;

public class TiShopMerchant {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.uuid
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private Integer uuid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.merchant_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String merchantId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.merchant_name
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String merchantName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.merchant_password
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String merchantPassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.shop_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private Integer shopId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.terminal_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String terminalId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.token
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String token;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.status
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private Short status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.bank
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String bank;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.batch_no
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String batchNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.pos_no
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String posNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.lmk_tmk
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String lmkTmk;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.lmk_tpk
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String lmkTpk;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.lmk_tak
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String lmkTak;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ti_shop_merchant.tmk_tak
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	private String tmkTak;
	private String updateTime;

	public String getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.uuid
	 *
	 * @return the value of ti_shop_merchant.uuid
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public Integer getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.uuid
	 *
	 * @param uuid
	 *            the value for ti_shop_merchant.uuid
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.merchant_id
	 *
	 * @return the value of ti_shop_merchant.merchant_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getMerchantId() {
		return merchantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.merchant_id
	 *
	 * @param merchantId
	 *            the value for ti_shop_merchant.merchant_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.merchant_name
	 *
	 * @return the value of ti_shop_merchant.merchant_name
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getMerchantName() {
		return merchantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.merchant_name
	 *
	 * @param merchantName
	 *            the value for ti_shop_merchant.merchant_name
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.merchant_password
	 *
	 * @return the value of ti_shop_merchant.merchant_password
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getMerchantPassword() {
		return merchantPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.merchant_password
	 *
	 * @param merchantPassword
	 *            the value for ti_shop_merchant.merchant_password
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setMerchantPassword(String merchantPassword) {
		this.merchantPassword = merchantPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.shop_id
	 *
	 * @return the value of ti_shop_merchant.shop_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public Integer getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.shop_id
	 *
	 * @param shopId
	 *            the value for ti_shop_merchant.shop_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.terminal_id
	 *
	 * @return the value of ti_shop_merchant.terminal_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getTerminalId() {
		return terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.terminal_id
	 *
	 * @param terminalId
	 *            the value for ti_shop_merchant.terminal_id
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.token
	 *
	 * @return the value of ti_shop_merchant.token
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.token
	 *
	 * @param token
	 *            the value for ti_shop_merchant.token
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.status
	 *
	 * @return the value of ti_shop_merchant.status
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.status
	 *
	 * @param status
	 *            the value for ti_shop_merchant.status
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.bank
	 *
	 * @return the value of ti_shop_merchant.bank
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getBank() {
		return bank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.bank
	 *
	 * @param bank
	 *            the value for ti_shop_merchant.bank
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setBank(String bank) {
		this.bank = bank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.batch_no
	 *
	 * @return the value of ti_shop_merchant.batch_no
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getBatchNo() {
		return batchNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.batch_no
	 *
	 * @param batchNo
	 *            the value for ti_shop_merchant.batch_no
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.pos_no
	 *
	 * @return the value of ti_shop_merchant.pos_no
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getPosNo() {
		return posNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.pos_no
	 *
	 * @param posNo
	 *            the value for ti_shop_merchant.pos_no
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setPosNo(String posNo) {
		this.posNo = posNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.lmk_tmk
	 *
	 * @return the value of ti_shop_merchant.lmk_tmk
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getLmkTmk() {
		return lmkTmk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.lmk_tmk
	 *
	 * @param lmkTmk
	 *            the value for ti_shop_merchant.lmk_tmk
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setLmkTmk(String lmkTmk) {
		this.lmkTmk = lmkTmk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.lmk_tpk
	 *
	 * @return the value of ti_shop_merchant.lmk_tpk
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getLmkTpk() {
		return lmkTpk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.lmk_tpk
	 *
	 * @param lmkTpk
	 *            the value for ti_shop_merchant.lmk_tpk
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setLmkTpk(String lmkTpk) {
		this.lmkTpk = lmkTpk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.lmk_tak
	 *
	 * @return the value of ti_shop_merchant.lmk_tak
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getLmkTak() {
		return lmkTak;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.lmk_tak
	 *
	 * @param lmkTak
	 *            the value for ti_shop_merchant.lmk_tak
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setLmkTak(String lmkTak) {
		this.lmkTak = lmkTak;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ti_shop_merchant.tmk_tak
	 *
	 * @return the value of ti_shop_merchant.tmk_tak
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public String getTmkTak() {
		return tmkTak;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ti_shop_merchant.tmk_tak
	 *
	 * @param tmkTak
	 *            the value for ti_shop_merchant.tmk_tak
	 *
	 * @mbggenerated Fri Aug 28 17:01:32 CST 2015
	 */
	public void setTmkTak(String tmkTak) {
		this.tmkTak = tmkTak;
	}
}