<message method="dividedpayment" type="response">
    <infoType>0210</infoType>
    <terminalID>%s</terminalID>
    <posID>%s</posID>
    <posTime>%s</posTime>
    <transDate>%s</transDate>
    <transTime>%s</transTime>
    <merchantID>%s</merchantID>
    <merchantName>%s</merchantName>
    <retCode>0000000</retCode>
    <commentRes>交易成功</commentRes>
    <batchNo>%s</batchNo>
    <serialNo>%s</serialNo>
    <orderID>%s</orderID>
    <pan>%s</pan>
    <bankOrderID/>
    <expiredDate/>
    <cvv2/>
    <chIdNum/>
    <chName/>
    <chMobile/>
    <productType>%s</productType>
    <productNum>%s</productNum>
    <payWay>%s</payWay>
    <transAmt>%s</transAmt>
    <currCode>%s</currCode>
    <dividedNum>%s</dividedNum>
    <inputType>%s</inputType>
    <posConditionCode>%s</posConditionCode>
    <secondTrack/>
    <thirdTrack/>
    <systemRefCode>161537021337</systemRefCode>
    <csc4/>
    <dynamicPwd/>
    <authorizeCode/>
    <authDate/>
    <authTime/>
    <timeStamp>%s</timeStamp>
    <signature>HT3za/ON5ceoNU4/NhD90+3U9Sz9CwKjfFvBSX0XYgbJuySeehyCDBRfQtA2f5/FGBzlUmwQST97Inx/klkW5HOf1UvEFVVPQp6G/xYrYrfqx+2987vdJTdjpjSLsiy4V8cI63rMaLLovtMlNpsi0tL5NM5VMAZG0eQxC+4+sEw=</signature>
    <reserved/>
</message>