package com.mocredit.manage.model;

import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.annotation.JSONField;

public class Contract {
	public static final Byte STATUS_PAUSE=0;
	public static final Byte STATUS_ACTIVED=1;
	public static final Byte STATUS_DELETED=2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.enterprise_id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String enterpriseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String name;
	private String signature;
	private String code;
	@JSONField (format="yyyy-MM-dd")  
	private Date startTime;
	@JSONField (format="yyyy-MM-dd")  
	private Date endTime;
	private String enterpriseName;
	private List<ContractMerchant> merchantList;
	
	

	public List<ContractMerchant> getMerchantList() {
		return merchantList;
	}

	public void setMerchantList(List<ContractMerchant> merchantList) {
		this.merchantList = merchantList;
	}

	public String getEnterpriseName() {
		return enterpriseName;
	}

	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getSignature() {
		return signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_contract.id
	 *
	 * @return the value of t_contract.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_contract.id
	 *
	 * @param id
	 *            the value for t_contract.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_contract.enterprise_id
	 *
	 * @return the value of t_contract.enterprise_id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_contract.enterprise_id
	 *
	 * @param enterpriseId
	 *            the value for t_contract.enterprise_id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_contract.create_time
	 *
	 * @return the value of t_contract.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_contract.create_time
	 *
	 * @param createTime
	 *            the value for t_contract.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_contract.status
	 *
	 * @return the value of t_contract.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_contract.status
	 *
	 * @param status
	 *            the value for t_contract.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_contract.name
	 *
	 * @return the value of t_contract.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_contract.name
	 *
	 * @param name
	 *            the value for t_contract.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}
}