package com.mocredit.manage.model;

public class ContractMerchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_merchant.id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_merchant.contract_id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_merchant.merchant_id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    private String merchantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_merchant.id
     *
     * @return the value of t_contract_merchant.id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_merchant.id
     *
     * @param id the value for t_contract_merchant.id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_merchant.contract_id
     *
     * @return the value of t_contract_merchant.contract_id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_merchant.contract_id
     *
     * @param contractId the value for t_contract_merchant.contract_id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_merchant.merchant_id
     *
     * @return the value of t_contract_merchant.merchant_id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_merchant.merchant_id
     *
     * @param merchantId the value for t_contract_merchant.merchant_id
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }
}