package com.mocredit.manage.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class Enterprise {
	public static final Byte STATUS_PAUSE=0;
	public static final Byte STATUS_ACTIVED=1;
	public static final Byte STATUS_DELETED=2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.code
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.linkman
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String linkman;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.linkphone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String linkphone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.linkman2
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String linkman2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.linkphone2
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String linkphone2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	@JSONField (format="yyyy-MM-dd HH:mm:ss")  
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.sms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer smsBalance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.sms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer smsTotal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.mms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer mmsBalance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.mms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer mmsTotal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.sms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer smsWarning;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.mms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer mmsWarning;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.mmschannle
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String mmschannle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_enterprise.audit
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer audit;

	private int activityCount;
	private int contractCount;
	private String linkaddress;
	
	public String getLinkaddress() {
		return linkaddress;
	}

	public void setLinkaddress(String linkaddress) {
		this.linkaddress = linkaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.id
	 *
	 * @return the value of t_enterprise.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.id
	 *
	 * @param id
	 *            the value for t_enterprise.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.name
	 *
	 * @return the value of t_enterprise.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.name
	 *
	 * @param name
	 *            the value for t_enterprise.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.code
	 *
	 * @return the value of t_enterprise.code
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.code
	 *
	 * @param code
	 *            the value for t_enterprise.code
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.linkman
	 *
	 * @return the value of t_enterprise.linkman
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.linkman
	 *
	 * @param linkman
	 *            the value for t_enterprise.linkman
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.linkphone
	 *
	 * @return the value of t_enterprise.linkphone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getLinkphone() {
		return linkphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.linkphone
	 *
	 * @param linkphone
	 *            the value for t_enterprise.linkphone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setLinkphone(String linkphone) {
		this.linkphone = linkphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.linkman2
	 *
	 * @return the value of t_enterprise.linkman2
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getLinkman2() {
		return linkman2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.linkman2
	 *
	 * @param linkman2
	 *            the value for t_enterprise.linkman2
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setLinkman2(String linkman2) {
		this.linkman2 = linkman2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.linkphone2
	 *
	 * @return the value of t_enterprise.linkphone2
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getLinkphone2() {
		return linkphone2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.linkphone2
	 *
	 * @param linkphone2
	 *            the value for t_enterprise.linkphone2
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setLinkphone2(String linkphone2) {
		this.linkphone2 = linkphone2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.status
	 *
	 * @return the value of t_enterprise.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.status
	 *
	 * @param status
	 *            the value for t_enterprise.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.create_time
	 *
	 * @return the value of t_enterprise.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.create_time
	 *
	 * @param createTime
	 *            the value for t_enterprise.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.sms_balance
	 *
	 * @return the value of t_enterprise.sms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getSmsBalance() {
		return smsBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.sms_balance
	 *
	 * @param smsBalance
	 *            the value for t_enterprise.sms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setSmsBalance(Integer smsBalance) {
		this.smsBalance = smsBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.sms_total
	 *
	 * @return the value of t_enterprise.sms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getSmsTotal() {
		return smsTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.sms_total
	 *
	 * @param smsTotal
	 *            the value for t_enterprise.sms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setSmsTotal(Integer smsTotal) {
		this.smsTotal = smsTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.mms_balance
	 *
	 * @return the value of t_enterprise.mms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getMmsBalance() {
		return mmsBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.mms_balance
	 *
	 * @param mmsBalance
	 *            the value for t_enterprise.mms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setMmsBalance(Integer mmsBalance) {
		this.mmsBalance = mmsBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.mms_total
	 *
	 * @return the value of t_enterprise.mms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getMmsTotal() {
		return mmsTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.mms_total
	 *
	 * @param mmsTotal
	 *            the value for t_enterprise.mms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setMmsTotal(Integer mmsTotal) {
		this.mmsTotal = mmsTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.sms_warning
	 *
	 * @return the value of t_enterprise.sms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getSmsWarning() {
		return smsWarning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.sms_warning
	 *
	 * @param smsWarning
	 *            the value for t_enterprise.sms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setSmsWarning(Integer smsWarning) {
		this.smsWarning = smsWarning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.mms_warning
	 *
	 * @return the value of t_enterprise.mms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getMmsWarning() {
		return mmsWarning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.mms_warning
	 *
	 * @param mmsWarning
	 *            the value for t_enterprise.mms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setMmsWarning(Integer mmsWarning) {
		this.mmsWarning = mmsWarning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.mmschannle
	 *
	 * @return the value of t_enterprise.mmschannle
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getMmschannle() {
		return mmschannle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.mmschannle
	 *
	 * @param mmschannle
	 *            the value for t_enterprise.mmschannle
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setMmschannle(String mmschannle) {
		this.mmschannle = mmschannle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_enterprise.audit
	 *
	 * @return the value of t_enterprise.audit
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getAudit() {
		return audit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_enterprise.audit
	 *
	 * @param audit
	 *            the value for t_enterprise.audit
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setAudit(Integer audit) {
		this.audit = audit;
	}

	public int getActivityCount() {
		return activityCount;
	}

	public void setActivityCount(int activityCount) {
		this.activityCount = activityCount;
	}

	public int getContractCount() {
		return contractCount;
	}

	public void setContractCount(int contractCount) {
		this.contractCount = contractCount;
	}

}