package com.mocredit.manage.model;

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

public class Merchant {
	public static final Byte STATUS_PAUSE = 0;
	public static final Byte STATUS_ACTIVED = 1;
	public static final Byte STATUS_DELETED = 2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.code
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.wap_url
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String wapUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.web_url
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String webUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.province
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.city
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer city;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.area
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer area;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.address
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.linkman
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String linkman;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.linkphone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String linkphone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.phone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.fax
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String fax;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.job_type
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer jobType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.sub_job_type
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer subJobType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	@JSONField (format="yyyy-MM-dd")  
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.sms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer smsBalance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.sms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer smsTotal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.mms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer mmsBalance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.mms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer mmsTotal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.sms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer smsWarning;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.mms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private Integer mmsWarning;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.mmschannle
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String mmschannle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.email
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_merchant.descr
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	private String descr;
	private int storeCount;

	public int getStoreCount() {
		return storeCount;
	}

	public void setStoreCount(int storeCount) {
		this.storeCount = storeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.id
	 *
	 * @return the value of t_merchant.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.id
	 *
	 * @param id
	 *            the value for t_merchant.id
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.name
	 *
	 * @return the value of t_merchant.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.name
	 *
	 * @param name
	 *            the value for t_merchant.name
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.code
	 *
	 * @return the value of t_merchant.code
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.code
	 *
	 * @param code
	 *            the value for t_merchant.code
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.wap_url
	 *
	 * @return the value of t_merchant.wap_url
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getWapUrl() {
		return wapUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.wap_url
	 *
	 * @param wapUrl
	 *            the value for t_merchant.wap_url
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setWapUrl(String wapUrl) {
		this.wapUrl = wapUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.web_url
	 *
	 * @return the value of t_merchant.web_url
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getWebUrl() {
		return webUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.web_url
	 *
	 * @param webUrl
	 *            the value for t_merchant.web_url
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setWebUrl(String webUrl) {
		this.webUrl = webUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.province
	 *
	 * @return the value of t_merchant.province
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.province
	 *
	 * @param province
	 *            the value for t_merchant.province
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setProvince(Integer province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.city
	 *
	 * @return the value of t_merchant.city
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.city
	 *
	 * @param city
	 *            the value for t_merchant.city
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setCity(Integer city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.area
	 *
	 * @return the value of t_merchant.area
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.area
	 *
	 * @param area
	 *            the value for t_merchant.area
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setArea(Integer area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.address
	 *
	 * @return the value of t_merchant.address
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.address
	 *
	 * @param address
	 *            the value for t_merchant.address
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.linkman
	 *
	 * @return the value of t_merchant.linkman
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.linkman
	 *
	 * @param linkman
	 *            the value for t_merchant.linkman
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.linkphone
	 *
	 * @return the value of t_merchant.linkphone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getLinkphone() {
		return linkphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.linkphone
	 *
	 * @param linkphone
	 *            the value for t_merchant.linkphone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setLinkphone(String linkphone) {
		this.linkphone = linkphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.phone
	 *
	 * @return the value of t_merchant.phone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.phone
	 *
	 * @param phone
	 *            the value for t_merchant.phone
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.fax
	 *
	 * @return the value of t_merchant.fax
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.fax
	 *
	 * @param fax
	 *            the value for t_merchant.fax
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.job_type
	 *
	 * @return the value of t_merchant.job_type
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getJobType() {
		return jobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.job_type
	 *
	 * @param jobType
	 *            the value for t_merchant.job_type
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setJobType(Integer jobType) {
		this.jobType = jobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.sub_job_type
	 *
	 * @return the value of t_merchant.sub_job_type
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getSubJobType() {
		return subJobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.sub_job_type
	 *
	 * @param subJobType
	 *            the value for t_merchant.sub_job_type
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setSubJobType(Integer subJobType) {
		this.subJobType = subJobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.status
	 *
	 * @return the value of t_merchant.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.status
	 *
	 * @param status
	 *            the value for t_merchant.status
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.create_time
	 *
	 * @return the value of t_merchant.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.create_time
	 *
	 * @param createTime
	 *            the value for t_merchant.create_time
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.sms_balance
	 *
	 * @return the value of t_merchant.sms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getSmsBalance() {
		return smsBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.sms_balance
	 *
	 * @param smsBalance
	 *            the value for t_merchant.sms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setSmsBalance(Integer smsBalance) {
		this.smsBalance = smsBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.sms_total
	 *
	 * @return the value of t_merchant.sms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getSmsTotal() {
		return smsTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.sms_total
	 *
	 * @param smsTotal
	 *            the value for t_merchant.sms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setSmsTotal(Integer smsTotal) {
		this.smsTotal = smsTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.mms_balance
	 *
	 * @return the value of t_merchant.mms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getMmsBalance() {
		return mmsBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.mms_balance
	 *
	 * @param mmsBalance
	 *            the value for t_merchant.mms_balance
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setMmsBalance(Integer mmsBalance) {
		this.mmsBalance = mmsBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.mms_total
	 *
	 * @return the value of t_merchant.mms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getMmsTotal() {
		return mmsTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.mms_total
	 *
	 * @param mmsTotal
	 *            the value for t_merchant.mms_total
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setMmsTotal(Integer mmsTotal) {
		this.mmsTotal = mmsTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.sms_warning
	 *
	 * @return the value of t_merchant.sms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getSmsWarning() {
		return smsWarning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.sms_warning
	 *
	 * @param smsWarning
	 *            the value for t_merchant.sms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setSmsWarning(Integer smsWarning) {
		this.smsWarning = smsWarning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.mms_warning
	 *
	 * @return the value of t_merchant.mms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public Integer getMmsWarning() {
		return mmsWarning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.mms_warning
	 *
	 * @param mmsWarning
	 *            the value for t_merchant.mms_warning
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setMmsWarning(Integer mmsWarning) {
		this.mmsWarning = mmsWarning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.mmschannle
	 *
	 * @return the value of t_merchant.mmschannle
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getMmschannle() {
		return mmschannle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.mmschannle
	 *
	 * @param mmschannle
	 *            the value for t_merchant.mmschannle
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setMmschannle(String mmschannle) {
		this.mmschannle = mmschannle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.email
	 *
	 * @return the value of t_merchant.email
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.email
	 *
	 * @param email
	 *            the value for t_merchant.email
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_merchant.descr
	 *
	 * @return the value of t_merchant.descr
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public String getDescr() {
		return descr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_merchant.descr
	 *
	 * @param descr
	 *            the value for t_merchant.descr
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	public void setDescr(String descr) {
		this.descr = descr;
	}
}