package com.mocredit.manage.model;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.id
     *
     * @mbggenerated Wed Nov 18 10:52:54 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.name
     *
     * @mbggenerated Wed Nov 18 10:52:54 CST 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.id
     *
     * @return the value of t_supplier.id
     *
     * @mbggenerated Wed Nov 18 10:52:54 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.id
     *
     * @param id the value for t_supplier.id
     *
     * @mbggenerated Wed Nov 18 10:52:54 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.name
     *
     * @return the value of t_supplier.name
     *
     * @mbggenerated Wed Nov 18 10:52:54 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.name
     *
     * @param name the value for t_supplier.name
     *
     * @mbggenerated Wed Nov 18 10:52:54 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}