package com.mocredit.manage.persitence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.mocredit.manage.model.Contract;

public interface ContractMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_enterprise
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	int deleteById(@Param("ids") List<String> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_enterprise
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	int insert(Contract record);

	List<Contract> selectAllForPage(Map<String, Object> map);

	Contract selectOne(@Param("id") String id);

	int update(Contract contract);

}