package com.mocredit.manage.persitence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mocredit.manage.model.ContractMerchant;

public interface ContractMerchantMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_enterprise
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	int deleteByContractId(@Param("ids") List<String> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_enterprise
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	int insertBatch(List<ContractMerchant> record);

	List<ContractMerchant> selectAllByContractId(@Param("contractId") String contractId);

}