package com.mocredit.manage.persitence;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.mocredit.manage.model.Enterprise;

public interface EnterpriseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_enterprise
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	int deleteById(@Param("ids") List<String> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_enterprise
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	int insert(Enterprise record);

	List<Enterprise> selectAllForPage(@Param("key") String key, @Param("startTime") Date startTime, @Param("endTime") Date endTime);

	Enterprise selectOne(@Param("id") String id);

	int update(Enterprise enterprise);

	Enterprise selectOneByName(Map<String, Object> param);
}