package com.mocredit.manage.persitence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.mocredit.manage.model.Merchant;

public interface MerchantMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_enterprise
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	int deleteById(@Param("ids") List<String> ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_enterprise
	 *
	 * @mbggenerated Mon Nov 02 15:47:55 CST 2015
	 */
	int insert(Merchant record);

	List<Merchant> selectAllForPage(Map<String, Object> param);

	Merchant selectOne(@Param("id") String id);

	int update(Merchant merchant);

	List<Merchant> selectAll();

	Merchant selectOneByName(Map<String, Object> param);
}