package com.mocredit.manage.persitence;

import java.util.List;

import com.mocredit.manage.model.Supplier;

public interface SupplierMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbggenerated Wed Nov 18 10:52:54 CST 2015
     */
    List<Supplier> selectAll();
}

