package com.mocredit.manage.persitence;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.mocredit.manage.model.Terminal;

public interface TerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    int deleteById(@Param("ids")List<String> ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Mon Nov 02 15:47:55 CST 2015
     */
    int insert(Terminal record);
    
    List<Terminal> selectAllForPage(Map<String, Object>param);
    Terminal checkSnCode(Map<String, Object>param);
    Terminal selectOne(@Param("id")String id);
    int update(Terminal terminal);
    Terminal selectStore(@Param("storeId")String storeId);
    
}