package com.mocredit.manage.persitence;

import java.util.List;

import com.mocredit.manage.model.TerminalType;

public interface TerminalTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_terminal_type
	 *
	 * @mbggenerated Wed Nov 18 10:52:54 CST 2015
	 */
	List<TerminalType> selectAll();
}