package com.mocredit.bank.persistence;

import com.mocredit.bank.entity.TiReportDataZx;

public interface TiReportDataZxMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_report_data_zx
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    int save(TiReportDataZx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ti_report_data_zx
     *
     * @mbggenerated Mon Aug 24 14:03:46 CST 2015
     */
    TiReportDataZx selectByReportId(int reportId);
}