package com.mocredit.manage.persitence;

import com.mocredit.manage.model.Area;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_area
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int insertSelective(Area record);
}