package com.mocredit.manage.persitence;

import com.mocredit.manage.model.BusinessType;

public interface BusinessTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_type
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_type
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int insert(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_type
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int insertSelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_type
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    BusinessType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_type
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int updateByPrimaryKeySelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_business_type
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int updateByPrimaryKey(BusinessType record);
}