package com.mocredit.manage.persitence;

import java.util.List;

import com.mocredit.manage.model.Contract;

public interface ContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int insert(Contract record);

    List<Contract> selectAll(Contract contract);
    Contract selectOne(Contract contract);
}