package com.mocredit.manage.persitence;

import com.mocredit.manage.model.Contract;

public interface ContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int insert(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int insertSelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    Contract selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int updateByPrimaryKeySelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int updateByPrimaryKey(Contract record);
}