package com.mocredit.manage.persitence;

import java.util.List;

import com.mocredit.manage.model.Enterprise;

public interface EnterpriseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int insert(Enterprise record);

    List<Enterprise> selectAll(Enterprise enterprise);
    Enterprise selectOne(Enterprise enterprise);
}