package com.mocredit.manage.persitence;

import com.mocredit.manage.model.Enterprise;

public interface EnterpriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int insert(Enterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int insertSelective(Enterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    Enterprise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int updateByPrimaryKeySelective(Enterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Enterprise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_enterprise
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int updateByPrimaryKey(Enterprise record);
}