package com.mocredit.manage.persitence;

import com.mocredit.manage.model.Strore;

public interface StroreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int insert(Strore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int insertSelective(Strore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    Strore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int updateByPrimaryKeySelective(Strore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    int updateByPrimaryKey(Strore record);
}