package com.mocredit.manage.persitence;

import com.mocredit.manage.model.Terminal;

public interface TerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int insert(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int insertSelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    Terminal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int updateByPrimaryKeySelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbggenerated Thu Oct 29 10:31:09 CST 2015
     */
    int updateByPrimaryKey(Terminal record);
}