package com.mocredit.manage.model;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.title
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.pid
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.sort_order
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.code
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_area.district
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String district;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.id
     *
     * @return the value of t_area.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.id
     *
     * @param id the value for t_area.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.title
     *
     * @return the value of t_area.title
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.title
     *
     * @param title the value for t_area.title
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.pid
     *
     * @return the value of t_area.pid
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.pid
     *
     * @param pid the value for t_area.pid
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.sort_order
     *
     * @return the value of t_area.sort_order
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.sort_order
     *
     * @param sortOrder the value for t_area.sort_order
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.code
     *
     * @return the value of t_area.code
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.code
     *
     * @param code the value for t_area.code
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_area.district
     *
     * @return the value of t_area.district
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_area.district
     *
     * @param district the value for t_area.district
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setDistrict(String district) {
        this.district = district;
    }
}