package com.mocredit.manage.model;

public class BusinessType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_type.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_type.title
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_type.pid
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_business_type.sort_order
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_type.id
     *
     * @return the value of t_business_type.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_type.id
     *
     * @param id the value for t_business_type.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_type.title
     *
     * @return the value of t_business_type.title
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_type.title
     *
     * @param title the value for t_business_type.title
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_type.pid
     *
     * @return the value of t_business_type.pid
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_type.pid
     *
     * @param pid the value for t_business_type.pid
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_business_type.sort_order
     *
     * @return the value of t_business_type.sort_order
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_business_type.sort_order
     *
     * @param sortOrder the value for t_business_type.sort_order
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
}