package com.mocredit.manage.model;

import java.util.Date;

public class Contract {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contract.id
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contract.enterprise_id
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	private Integer enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contract.create_time
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_contract.status
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contract.id
	 * @return  the value of t_contract.id
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contract.id
	 * @param id  the value for t_contract.id
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contract.enterprise_id
	 * @return  the value of t_contract.enterprise_id
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contract.enterprise_id
	 * @param enterpriseId  the value for t_contract.enterprise_id
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contract.create_time
	 * @return  the value of t_contract.create_time
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contract.create_time
	 * @param createTime  the value for t_contract.create_time
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_contract.status
	 * @return  the value of t_contract.status
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_contract.status
	 * @param status  the value for t_contract.status
	 * @mbggenerated  Thu Oct 29 10:31:09 CST 2015
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}