package com.mocredit.manage.model;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.name
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.code
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.merchant_id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.province
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.city
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.area
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Integer area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.address
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.longitude
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.latitude
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.status
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.mobile
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_store.phone
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.id
     *
     * @return the value of t_store.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.id
     *
     * @param id the value for t_store.id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.name
     *
     * @return the value of t_store.name
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.name
     *
     * @param name the value for t_store.name
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.code
     *
     * @return the value of t_store.code
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.code
     *
     * @param code the value for t_store.code
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.merchant_id
     *
     * @return the value of t_store.merchant_id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.merchant_id
     *
     * @param merchantId the value for t_store.merchant_id
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.province
     *
     * @return the value of t_store.province
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.province
     *
     * @param province the value for t_store.province
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.city
     *
     * @return the value of t_store.city
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.city
     *
     * @param city the value for t_store.city
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.area
     *
     * @return the value of t_store.area
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.area
     *
     * @param area the value for t_store.area
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.address
     *
     * @return the value of t_store.address
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.address
     *
     * @param address the value for t_store.address
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.longitude
     *
     * @return the value of t_store.longitude
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.longitude
     *
     * @param longitude the value for t_store.longitude
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.latitude
     *
     * @return the value of t_store.latitude
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.latitude
     *
     * @param latitude the value for t_store.latitude
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.status
     *
     * @return the value of t_store.status
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.status
     *
     * @param status the value for t_store.status
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.mobile
     *
     * @return the value of t_store.mobile
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.mobile
     *
     * @param mobile the value for t_store.mobile
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_store.phone
     *
     * @return the value of t_store.phone
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_store.phone
     *
     * @param phone the value for t_store.phone
     *
     * @mbggenerated Thu Oct 29 12:05:06 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}